### ISSUE TITLE
Additional over keyboard : Ability to use them while fast typing (Move finger slightly away while pressing)

### ISSUE THREAD

**Issue by MrFly72** [isontheline/pro.webssh.net#618] opened 2022-05-15 17:59 UTC
# Bug description
When using the additional keys on an iPad Pro (2021) I often need to press them slow or double for the key t9 show u0. Started to use the original keyboard rather than the additional keys, as they react really slow. It can not be a performance problem, as the iPad Pro M1 should have plenty of performance 
I am using the latest testflight

**Comment by isontheline** [comment] 2022-05-15 18:13
Hello @MrFly72 👋

What are the additional keys `t9` `u0` ?

I don't have understand your trouble, I'm sorry I don't own an iPad Pro (only mini)

**Comment by MrFly72** [comment] 2022-05-15 18:36
Hi there.

I mean these keys:
![image](https://user-images.githubusercontent.com/65505278/168488571-315ccb70-c698-4bbf-bcaf-7c25920ee518.jpeg)

**Comment by isontheline** [comment] 2022-05-15 19:01
OK I now understand, thank you a lot for your feedback 🙏

I'm planning a fix for this trouble.

Thank you again

**Comment by isontheline** [comment] 2022-05-24 20:10
Found why :
<img width="789" alt="image" src="https://user-images.githubusercontent.com/44212923/170123228-1b910054-9aee-436e-a9ea-28a1c256be14.png">

You (yet) need to release your finger "inside" the buttons and not outside.

**Comment by MrFly72** [comment] 2022-05-24 20:26
Ok, that might be the reason why it "feels" not behaving, but sometimes it does. 
Will this be fixed?

**Comment by isontheline** [comment] 2022-05-25 05:37
I think it's possible to improve this behavior.

I will try soon

**Comment by AInteriorB** [comment] 2022-05-26 20:01
> Ok, that might be the reason why it "feels" not behaving, but sometimes it does. It might be also so difficult, as the button is smaller then all others.
> Will this be fixed?

I cannot confirm this is an issue. All virtual keys react instantly here on an iPad Pro.

**Comment by isontheline** [comment] 2022-05-26 20:23
@AInteriorB Never missed a tap on these keys so?

**Comment by MrFly72** [comment] 2022-05-27 05:00
I mean they react instantly when I Test only the button and concentrate on it 😉
But in faster typing and not hitting the right spot or as the developer stated move slightly away while pressing, the button will not react anymore. Have you tried pressing the button and move slightly up.

**Comment by isontheline** [comment] 2022-05-27 19:36
I will make an improvement in order to have a more robust solution for fast typing 😉

**Comment by isontheline** [comment] 2022-06-11 20:18
From Nick :
> Hey Arnoud(and apple), i have this weird glitch for a while if i type fast and try to hit the charater - then it changes to the i. It took me some time that it is a glitch in the keyboard and not a misclick. So if type apt-get, it will hit the i and not the - while you hit the charater - Regards Nick.

![image](https://user-images.githubusercontent.com/44212923/173203570-59e32075-10b9-4eec-9a5b-5a18fcf08b68.png)

**Comment by MrFly72** [comment] 2022-07-30 20:47
Any news on this?

**Comment by isontheline** [comment] 2022-07-31 19:09
Hello @MrFly72 👋

Not yet tried due to lack of time. I'm late on all issues.

If it's a really bad behavior for you, I will try to fix it in the current major releases.
I can't tell any ETA but I will do my best efforts in order to fix it within August.

**Comment by isontheline** [comment] 2022-08-09 20:19
@MrFly72 
I'm improving the "outside touch release" :

![Image](https://user-images.githubusercontent.com/44212923/183752267-f7084556-e506-4f3c-a242-b07dc545e585.png)

RED : New function added to map outside touch release
YELLOW : The maximum distance (pixels) allowed from outside
GREEN : Warning => when you hit the "empty" line between "i" and "-" => "i" will be chosen by the Operating System

I will beta release this improvement in a few hours but I will not be able to make any further improvements like this (due to GREEN empty line between the keyboard and the accessories view).

**Comment by isontheline** [comment] 2022-08-09 20:48
@MrFly72 Please find the latest beta release on TestFlight : 
https://testflight.apple.com/join/QSrBK59z

**Comment by isontheline** [comment] 2022-08-10 04:04
I can confirm that my fix is almost useless : when you fast type on the letters the operating system have an error prone system which let you to press the "good" key.

So when you fast type and press an accessory button, if your finger isn't on the top of the accessory button only the operating system keyboard button will be pressed.

Tried the same on Termius and able to reproduce the issue.

I'm sorry it will be hard to enhance this default operating system behavior.

**Comment by MrFly72** [comment] 2022-08-10 06:40
You can really with Termius?
I cannot.
I can even touch the button "-" and move my finger down even to a eg. An "f" and the "-" will appear (keeping the finger on the keyboard).

**Comment by isontheline** [comment] 2022-08-10 08:59
I'm looking at it again

**Comment by isontheline** [comment] 2022-08-10 20:42
@MrFly72 Could you try WebSSH Beta 19.6.958?
Thank you

**Comment by MrFly72** [comment] 2022-08-10 20:50
Wow. Looks good to me. 
It's late now here, so could only do some small testing, but it looks really good in the first tests!

**Comment by isontheline** [comment] 2022-08-11 04:00
@MrFly72 No problem, thank you a lot for your first feedback

**Comment by MrFly72** [comment] 2022-08-11 19:30
Looks great so far.
Only thing I noticed: CTRL button will now send a CTRL+C when moving down while pressing. Did not know that press and hold on the button gives more options.
Also ESC Button will change to ALT when moving down while pressing.
Don't know what of this is intended behavior.

**Comment by isontheline** [comment] 2022-08-11 19:32
@MrFly72 

Not intended to send Ctrl-C or switch ESC to ALT when moving down, only when long pressing.

I'm fixing these bugs.

Thank you a lot for your feedback!

**Comment by isontheline** [comment] 2022-08-11 20:11
After double-check, all are intended

**Closed** 2022-08-12 20:56 UTC
Labels: ✨ enhancement
