### ISSUE TITLE
Sessions and tabs improvements

### ISSUE THREAD

**Issue by jarrah31** [isontheline/pro.webssh.net#624] opened 2022-05-17 07:53 UTC
# Bug description
Clicking open sessions from the sessions group in the sidebar causes them to open in whichever tab you are working in, rather than jumping to the tab that session was opened from. The original tab ends up having an empty panel.

This also results in the tab staying open when you ctrl+d quit a session. 

# Steps to reproduce
1. Start a new SSH session within a tab
2. Open a new 2nd tab and start another session with a different server. 
3. With the 2nd tab open, select the session in the sidebar from the 1st tab
4. The 1st session opens in the 2nd tab. I would expect it to swap to the 1st tab.
5. The 1st tab has an empty panel
6. Quitting the 1st session results in the 1st tab remaining open.

**Comment by isontheline** [comment] 2022-05-17 08:03
In my point of view it’s not a bug because I have « cloned » some other apps concepts (like Rayon ssh app)

At this time I’m unable to focus a tab which contains the selected connection view controller.

The Rayon app do a « great » thing : when a connection is re-attached to another tab, the « zombie » tab isn’t blank but instead display a message : « Terminal was transfered to another window »

I understand that the current WebSSH workflow has a trouble. I need to improve it with your feedbacks.

**Comment by jarrah31** [comment] 2022-05-17 08:14
I understand now, that's fine with me if it's an expected behaviour. 

Yes, improving the message in the tabs would help explain what it's doing. I like the « Terminal was transferred to another window » suggestion for the tab title.

I've noticed that on a tab where the session was moved from (so is now empty), if I then click an open session to appear in that tab again and then quit the session, the main tab window doesn't revert back to the list of Connections.

Also, in the steps above, at step 3 when I select the 1st tab sessions, the tab title says WebSSH rather than the session name. If I then subsequently swap to other sessions, the correct names always appears.

**Comment by jarrah31** [comment] 2022-05-17 08:43
Would it also be possible to close a session from the sidebar sessions list please? Perhaps the ability to right-click a session and close from the menu pop-up?
I guess on an iPad you could swipe left the session to reveal a red trash icon?

**Comment by isontheline** [comment] 2022-05-17 19:27
> I've noticed that on a tab where the session was moved from (so is now empty), if I then click an open session to appear in that tab again and then quit the session, the main tab window doesn't revert back to the list of Connections.
> 
> Also, in the steps above, at step 3 when I select the 1st tab sessions, the tab title says WebSSH rather than the session name. If I then subsequently swap to other sessions, the correct name always appears.

Thank you for your feedback! I will fix / improve these issues.

> Would it also be possible to close a session from the sidebar sessions list please? Perhaps the ability to right-click a session and close from the menu pop-up?
> I guess on an iPad you could swipe left the session to reveal a red trash icon?

RC2 already contains this improvement :
<img width="251" alt="image" src="https://user-images.githubusercontent.com/44212923/168894100-79c79ff6-e5c7-4518-9b83-a58b57e3957d.png">

It will be shipped in a few hours 😅

**Comment by jarrah31** [comment] 2022-05-18 07:10
It works great, thank you!

**Comment by isontheline** [comment] 2022-05-24 20:00
@jarrah31 "Empty panels" behavior shouldn't occurs anymore since WebSSH 18.1 :
https://testflight.apple.com/join/QSrBK59z

**Comment by jarrah31** [comment] 2022-05-24 20:11
Hi Arnaud, yes I can confirm that now works - thank you!

**Comment by isontheline** [comment] 2024-03-03 20:16
Hello @jarrah31 👋
I'm closing it as I've read it twice and didn't found no finished tasks.

Of course if I'm wrong please tell me

I wish you a nice day ☀️

**Closed by isontheline** 2024-03-03 20:16 UTC
Labels: ✨ enhancement
