### ISSUE TITLE
WebSSH port forwarding on iOS 16 does not function if WebSSH is not active window

### ISSUE THREAD

**Issue by ksylvan** [isontheline/pro.webssh.net#742] opened 2022-09-29 22:09 UTC
# Bug description
WebSSH to port forward localhost:XYZ to a remote port is not active in the background.

# Steps to reproduce
1. Use port forwarding to tunnel localhost:XYZ to some remote port.
2. Bring up a web browser and try to access localhost:XYZ
3. The web page is not rendered.
4. In iPadOS, use split-view to bring up WebSSH in Split View so both WebSSH and the browser are active.
5. Now, the web page is rendered.

**Comment by isontheline** [comment] 2022-09-30 04:02
Hello @ksylvan 

It's not a bug you need to enable VPN-Over-SSH check box inside your tunnel settings.

**Comment by ksylvan** [comment] 2022-09-30 14:41
Thank you.

**Comment by isontheline** [comment] 2022-10-01 16:17
You're right but I afraid I can't do anything more, only one VPN at a time can be launched.

I'm closing this issue yet because the port forwarding feature works as it should.

**Closed by isontheline** 2022-10-01 16:17 UTC

**Comment by ksylvan** [comment] 2022-10-05 20:00
I was able to do what I wanted with the Termius App on iPadOS. The trick was that turning on location services for the app allows it to keep working in the background.

Here's their support article about this:

https://support.termius.com/hc/en-us/articles/900006226306-I-can-t-use-the-iOS-app-in-the-background

Maybe you can do something like this for an upcoming release, which would also eliminate the need for the VPN-Over-SSH VPN profile and allow WebSSH to be used in combination with other VPNs.
