### ISSUE TITLE
X Does not close the error notification

### ISSUE THREAD

**Issue by ash34** [isontheline/pro.webssh.net#786] opened 2022-11-28 08:17 UTC
iPad and MocOS 

When the connection fails the error message shows an X symbol. It is assumed that this can be used to dismiss the message but it does not.

<img width="1016" alt="Screenshot 2022-11-23 at 13 31 57" src="https://user-images.githubusercontent.com/56022918/204226314-031a2ede-91e5-452a-a12e-adb8ce26fcae.png">

# Steps to reproduce
1. Begin a connection to a non-existent server to provoke the error message
2. Observe the error message and try to close it
3. Observe that selecting anywhere else on the screen except the X closes the error message

**Comment by isontheline** [comment] 2022-11-28 18:43
I'm sorry but it's not the intended behavior. The purpose of the X symbol is only to represent the message type : information / warning / error

The dismiss should happen when clicking-out as it's implemented under iOS.

**Comment by isontheline** [comment] 2022-12-23 20:51
I'm considering now this issue

**Comment by isontheline** [comment] 2022-12-23 20:54
Will use these statements : https://github.com/SwiftKickMobile/SwiftMessages#interaction

**Comment by isontheline** [comment] 2022-12-23 21:33
This is now fixed inside the latest beta release : https://testflight.apple.com/join/QSrBK59z

**Closed by isontheline** 2022-12-23 21:33 UTC
Labels: ✨ enhancement
