### ISSUE TITLE
keeps loosing connection

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#777] opened 2022-11-22 20:42 UTC
# Bug description
If I am logged in to a machine via WebSSH and I move to other windows for a while and come back the connection looks alive but I can't do anything for quite a long time. It may eventually "come alive". Closing that connection and reopening "fixes" but is tedious. 

# Screenshots
_If applicable, add screenshots to help explain your problem_

# Steps to reproduce
1. Login to a machine.
2. Move focus for a while to another window
3. Return to WebSSH
4. Error is thrown

Version 20.4 (1000)

**Comment by isontheline** [comment] 2022-11-22 20:43
Does network have been paused?

**Comment by mbierman** [comment] 2022-11-22 20:49
No change to the network.

**Comment by isontheline** [comment] 2022-11-22 20:52
Thanks for your feedback @mbierman I will check

Sometimes it could happen when too many processes are opened and macOS is requiring memory : I'm facing this issue and need to find the root cause

**Comment by mbierman** [comment] 2022-11-22 21:02
Memory doesn't seem to be taxed—but I will keep an eye on that when this happens and see if I can reproduce.

**Comment by isontheline** [comment] 2022-12-01 20:13
Under iOS and iPadOS there are a lot of rules that Apple run in order to keep your battery level safe.

If you are using macOS, please provide :
* your operating system version
* your operating system uptime
* your operating system free memory

**Comment by mbierman** [comment] 2022-12-03 06:49
The machine I use most often  has no battery. It is a macmini. 
macOS 13.0.1 (22A400)
22:26  up 11 days,  3:10, 4 users, load averages: 2.72 2.63 1.93
<img width="621" alt="image" src="https://user-images.githubusercontent.com/1205471/205428021-3e4b1ccc-948e-4b15-8529-8e1fff64763b.png">

I also have a a macbook pro. I think it happens on this machine too but I don't use it equally so it is hard to say definitively. 
1.7 GHz Quad-Core Intel Core i7
13.0.1 (22A400)

I'm not seeing the issue on iOS. 

I don't think I have seen this issue on iOS.

**Comment by isontheline** [comment] 2022-12-03 06:52
That's perfect @mbierman !

Are you seeing an increase since upgrading to Ventura?

I will make my best efforts to resolve this issue

**Comment by isontheline** [comment] 2022-12-03 20:54
Yet I can't reproduce on MacBook Air macOS 13.0.1

**Comment by mbierman** [comment] 2022-12-03 21:48
I did not see this issue before Ventura.

**Comment by isontheline** [comment] 2022-12-05 11:23
Possible root cause identified : under Ventura (more agressive than before) the WKWebView is reloaded (didNavigationFinish) but the terminal is in a "zombie" state.

If you use tmux you shouldn't see this trouble.

If you don't use tmux, most often the screen will be "dark" (or background color you have choosed). Could you confirm @mbierman ?

I'm searching for a fix.

**Comment by isontheline** [comment] 2022-12-05 20:42
For @isontheline work :
* http://github.com/ionic-team/cordova-plugin-ionic-webview/blob/ab7dfc06a7f8780f75800dae4f4217d1956aa7b6/src/ios/CDVWKWebViewEngine.m#L178
* http://gist.github.com/jasonbekolay/dad7c446ae1b02f174dc3eb3a5ea70ee
* http://github.com/xtermjs/xterm.js/blob/master/addons/xterm-addon-serialize/typings/xterm-addon-serialize.d.ts
* http://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-serialize
* http://github.com/xtermjs/xterm.js/issues/3364
* http://github.com/cyrus-and/ratty/commit/443da06de8c66870d3ded13d2d35d67ffeaee6d3

**Comment by mbierman** [comment] 2022-12-05 20:54
I appreciate that so much! I will look forward to trying it out.

**Comment by isontheline** [comment] 2022-12-07 21:35
A first fix attempt will be released in a few hours.

The fix will be made in two steps :
1. Reloading the terminal view (prevent locking as you are encountering) when killed by macOS (due to aggressive memory pressure management under Ventura)
2. Reloading the scrollback buffer in order to scroll the history as usual

The first step will let you to use WebSSH again when kills occur.
The second will try to make the kill "transparent".

**Comment by mbierman** [comment] 2022-12-07 22:08
Fantastic! Thank you and I will update here with any feedback.

**Comment by isontheline** [comment] 2022-12-08 20:15
You're Welcome @mbierman 

Last update 20.6.1011 is available on TestFlight.

TestFlight is however encountering some problems these last hours :
https://developer.apple.com/forums/search/?q=testflight&page=1&sortBy=lastUpdated

**Comment by isontheline** [comment] 2022-12-09 20:23
@mbierman TestFlight should work now

**Comment by mbierman** [comment] 2022-12-09 21:42
I see it on iOS but the problem I was having was mostly on macOS.

**Comment by isontheline** [comment] 2022-12-10 06:36
@mbierman Invitation have been sent

**Comment by mbierman** [comment] 2022-12-10 08:17
Thank you!

**Comment by isontheline** [comment] 2022-12-10 21:39
Build 1013 now tries to restore the terminal state (as much as it can).

**Closed** 2022-12-11 21:58 UTC
Labels: 🐛 bug
