### ISSUE TITLE
Unwanted screen refresh

### ISSUE THREAD

**Issue by mbierman** [isontheline/pro.webssh.net#801] opened 2022-12-29 22:28 UTC
# Bug description
I think the memory fix is having an unfortunate and unintended site effect of refreshing the screen. Observe video. When coming back, the shell must be where it was left. Destroying the current state is a horrible experience. 

# Screenshots
https://youtu.be/dHyC2WBxHqE

# Steps to reproduce
1. Use webssh
2. change windows
3. Return to Webssh
4. Screen may be cleared

**Comment by isontheline** [comment] 2022-12-30 20:19
Thank you @mbierman for your report. 
I will make a fix asap.

**Comment by mbierman** [comment] 2022-12-30 20:23
@isontheline  🙇🏻‍♂️ 🙏🏻

**Comment by mbierman** [comment] 2023-01-08 00:54
Let me know how I can help. Still happening for me. Almost always after I've moved to other screens especially if i use Mission Control to go to another screen.

**Comment by isontheline** [comment] 2023-01-08 07:15
I have tried with mission control but can't reproduce each time.

I'm so killing the WKWebView process in order to simulate the same behavior as you.

This problem will be fixed soon I think.

**Comment by mbierman** [comment] 2023-01-09 00:43
Thank you! I'm happy to test anything if it helps.

**Comment by mbierman** [comment] 2023-01-11 04:27
is Version 21.2 (1029) the latest?

**Comment by isontheline** [comment] 2023-01-11 05:03
Yes it's the latest 
😞
On my side when I kill the WebKit process the scrollback buffer is restored as expected.

OK I'm reopening this issue

**Comment by mbierman** [comment] 2023-01-11 05:17
Sorry! Please let me know if I can help in any way.

**Comment by isontheline** [comment] 2023-01-11 05:39
Thank you @mbierman 🙏

I will release another fix tonight.

Sorry for the trouble

**Comment by mbierman** [comment] 2023-01-11 05:40
Not at all! I appreciate all your work. I'll keep my eyes open.

**Comment by mbierman** [comment] 2023-01-12 06:38
Hi I have been using it on and off today. It can still be up to 20-35 seconds for it to be responsive. Is there any kind of debugging or trace i can run and share with you?

**Comment by isontheline** [comment] 2023-01-12 08:24
Hi

No logs to share as I don't know where to put them as long as I can't reproduce on my side every time.

Unresponsive or "not focused" to accept keyboard inputs?

Does the scrollback state restoration is working as expected?

**Comment by isontheline** [comment] 2023-01-13 20:12
tmux could also be used as a workaround while the root cause isn't caught and fixed

**Comment by isontheline** [comment] 2023-01-17 06:45
Hi @mbierman 

May I ping you about https://github.com/isontheline/pro.webssh.net/issues/801#issuecomment-1379967024

I would like to know if the scrollback buffer is now restored as expected (but unresponsive) ?

**Comment by mbierman** [comment] 2023-01-19 05:30
Mostly yes. But today briefly I had the webssh screen flash up but then come back. I think that's the first time I saw that. I'll pay more attention and see if I can capture anything for you.

**Comment by mbierman** [comment] 2023-01-19 08:06
@isontheline so I just had an example. I'll do my best to explain. 

I was editing using vi in webssh. I could navigate around: up line, down line, etc. but could not save the document. It finally occurred to me it might be a screen update issue. I switched spaces and the refresh happened and I could save the document.

**Comment by isontheline** [comment] 2023-01-19 19:31
Thanks @mbierman for your feedback!

It's strange that you can't save the file as the editor is behind the SSH and it's not managed by WebSSH itself (only rendering what the vi app want).

But I'm OK that WebSSH have a bad rendering issue since macOS Ventura.
A new Ventura minor release will be shipped last week. I'm waiting for it to check if the trouble is gone or not.

**Comment by mbierman** [comment] 2023-01-20 22:28
I think the issue is that either I can't see the screen update and/or there is a disconnect of keystrokes when this is happening because even after it is restored the keystrokes never made it through.

**Comment by isontheline** [comment] 2023-01-21 11:29
Does a reboot decrease the troubles occurrences? Or not at all?

**Comment by MKC-MKC** [comment] 2023-02-05 12:43
too
https://github.com/isontheline/pro.webssh.net/issues/812

**Comment by isontheline** [comment] 2023-02-05 17:20
@MKC-MKC Thanks for your feedback.

Could make a video about the trouble encountered? (Like you have done privately by email about the keyboard issue)?

**Comment by MKC-MKC** [comment] 2023-02-05 17:23
> @MKC-MKC Thanks for your feedback.
> 
> Could make a video about the trouble encountered? (Like you have done privately by email about the keyboard issue)?

video here: https://github.com/isontheline/pro.webssh.net/issues/812#issuecomment-1417667198

**Comment by isontheline** [comment] 2023-02-05 17:28
@MKC-MKC The video is about your keyboard issue. This issue is about screen refresh and data loss.

Are you sure?

**Comment by MKC-MKC** [comment] 2023-02-05 17:49
> @MKC-MKC The video is about your keyboard issue. This issue is about screen refresh and data loss.
> 
> Are you sure?

yes. details in email

**Comment by isontheline** [comment] 2023-03-11 21:35
> This may be related to the other reported bug around memory issues and screen refreshes. I've noticed that when I have 6 or more open sessions in MacOS that the session windows will randomly clear and then return. Sometimes they return with a new line at the top. Other times they come back with the full text that was previously displayed, but the action of reading it in looks like the incorrect font size for a moment, before it fixes itself.
> 
> Ventura 13.2.1
> 
> I'll try to capture a video but it's transient.

From @sbrooke

**Comment by isontheline** [comment] 2023-03-18 20:02
I don't forget anyone facing to this issue.

I also encounter these troubles on my side but it's hard for me to reproduce with the debugger attached.
I'm using tmux right now to prevent these troubles.

I WILL fix this issue, it's my red line.
Sorry to anyone facing to this issue.

**Comment by isontheline** [comment] 2023-04-27 11:22
For @isontheline work :
* https://github.com/ionic-team/capacitor/discussions/5260 
* https://github.com/ionic-team/capacitor/discussions/5488 
* https://developer.apple.com/forums/thread/721170 
* https://developer.apple.com/forums/thread/723731

**Comment by isontheline** [comment] 2023-04-27 11:25
Hello @mbierman @MKC-MKC 

Could you try to run these steps in order to be sure that memory pressure is the root cause?
1. Launch WebSSH
2. Launch a SSH connection
3. Launch the macOS "Terminal" app (cover some parts of WebSSH)
4. Run this command : `sudo memory_pressure -S -l critical`

Are you seeing that WebSSH subprocess has been killed and the refresh happened?

**Comment by isontheline** [comment] 2023-04-28 19:54
Thank you @MKC-MKC

**Comment by isontheline** [comment] 2023-05-02 19:17
Hello @MKC-MKC 👋

When the keyboard doesn't work : does the cursor is blinking?

**Comment by sbrooke** [comment] 2023-05-02 20:50
It does not for me. No blinking.

**Comment by isontheline** [comment] 2023-05-03 19:54
@MKC-MKC Could you confirm me that the cursor is blinking when all is OK and not-blinking when a problem has occured?

**Comment by MKC-MKC** [comment] 2023-05-04 14:52
> @MKC-MKC Could you confirm me that the cursor is blinking when all is OK and not-blinking when a problem has occured?

Cursor always blinking. see in vid
https://disk.yandex.com/i/YRNMUBf8ymne_w

**Comment by isontheline** [comment] 2023-05-04 19:45
Thank you @sbrooke 🙏

I'm checking why the WKWebView is crashing

**Comment by isontheline** [comment] 2023-06-01 05:26
WebSSH 22.2.1101 has been released.
As I can't prevent the kill by the operating system I have improved the restoration system.

Now a headless terminal run in parallel of the displayed one and sync the state when needed.

**Comment by isontheline** [comment] 2023-06-04 19:36
Being pushed to the App Store

**Closed by isontheline** 2023-06-04 19:36 UTC
Labels: 🐛 bug
