### ISSUE TITLE
Starting Powershell in WebSSH Session has problems

### ISSUE THREAD

**Issue by MrFly72** [isontheline/pro.webssh.net#433] opened 2021-10-10 18:46 UTC
**Describe the bug**
Connecting by SSH to a raspi and then changing to a powershell console (calling pwsh) leads to problems in WebSSH but not in other SSH Clients. Any clue what could produce this problem? Keepalive keys?

**Informations**
 - Device : iPad Pro 2021 11''
 - OS : ios 15.0.1
 - WebSSH Pro version : 16.1.3 (Testflight, but also latest production has this problem for me)

https://user-images.githubusercontent.com/65505278/136709284-4ba182af-f7af-4227-879a-fdb3ddcdf50d.MP4

**Comment by isontheline** [comment] 2021-10-10 19:14
Hello @MrFly72 👋

Thanks for your issue 🙏

I'm checking on my side. 

I will come back to you shortly.

**Comment by MrFly72** [comment] 2021-10-10 19:19
One more point with this. PWSH seems to take a lot longer to start with WebSSH Session than it does with other SSH clients. Dont know why though......

**Comment by isontheline** [comment] 2021-10-10 19:37
I can reproduce, that's strange.

I think I need to update the rendering engine.

**Comment by isontheline** [comment] 2021-10-10 19:52
Yes it's a strange use case 😜 but I will check why it don't work 😉

**Comment by MrFly72** [comment] 2021-10-10 20:15
That's mine: https://github.com/MrFly72/Synology_Mediathek_Download
Although I should update the code with recent changes. 
working on some stuff for Raspi, to make it better usable via shell

**Comment by MrFly72** [comment] 2021-11-20 10:54
Any news on the timeframe? I am on the beta track but so far 17 seems not be in beta?

**Comment by isontheline** [comment] 2021-11-20 13:01
Hello @MrFly72 

I'm late sorry.
No ETA yet.

[16.2](https://github.com/isontheline/pro.webssh.net/milestone/26) isn't done.

**Comment by MrFly72** [comment] 2021-12-24 19:14
Still no timeframe?

**Comment by isontheline** [comment] 2021-12-25 10:01
Still no ETA, I'm busy on fixes over 16.X release.

While waiting you could use [Termius](https://apps.apple.com/us/app/termius-ssh-client/id549039908) which has a better rendering engine than WebSSH.

**Comment by isontheline** [comment] 2022-01-29 21:06
I'm working on it.

It's strange, even with the new rendering engine there are glitches with PWSH. 
But no glitches by using macOS terminal 😢

I'm searching the root cause

**Comment by MrFly72** [comment] 2022-01-31 20:43
Sound like a weird problem.

**Comment by MrFly72** [comment] 2022-02-08 19:41
Any news? Did you find something?

**Comment by isontheline** [comment] 2022-02-08 20:24
Not yet
This behavior is so strange

**Comment by MrFly72** [comment] 2022-03-19 13:46
Any news on this? It still breaks also with PWSH 7.2.2

**Comment by isontheline** [comment] 2022-03-19 16:27
I need to compare streams between WebSSH and macOS Terminal app.
I think "standard" terminal apps are sending options and WebSSH not.

I will look at this tomorrow on Sunday 19th, March

**Comment by isontheline** [comment] 2022-03-20 19:24
@MrFly72 When launching pwsh inside tmux it works great! 
That's so strange!

```
tmux
pwsh
```

**Comment by MrFly72** [comment] 2022-03-20 21:00
Yes it is. Also installed tmux now and thanks for that hint, tried "screen" before, but it looks tmux is quite nice.
Nevertheless very weird problem

**Comment by isontheline** [comment] 2022-03-21 20:41
Powershell is requesting cursor position :
```
=========================================
Packet received 2022-03-21 20:35:50 +0000
=========================================
1b: 5b:[ 36:6 6e:n                                                                                   [6n

=========================================
Packet received 2022-03-21 20:35:51 +0000
=========================================
1b: 5b:[ 36:6 6e:n                                                                                   [6n
```

But WebSSH doesn't tell him where the cursor is.

I think this is the root cause.

I'm trying to return cursor position to pwsh.

**Comment by isontheline** [comment] 2022-03-21 20:58
I'm on a good way to fix it

**Comment by isontheline** [comment] 2022-03-22 06:26
@MrFly72 Fixed on WebSSH beta 17.4

<img width="514" alt="image" src="https://user-images.githubusercontent.com/44212923/159420654-67cfeb57-b6a1-4763-a4b3-1ddbfc0ce785.png">

Will be available for download tonight : 
https://testflight.apple.com/join/QSrBK59z

**Comment by MrFly72** [comment] 2022-03-22 06:55
I will test it right away ;-)
i am already joined to testflight since some months and only using the testflight releases.

**Comment by isontheline** [comment] 2022-03-22 17:05
Now released on TestFlight

**Closed as completed by isontheline** 2022-03-22 17:05 UTC
Labels: 🐛 bug
