### ISSUE TITLE
DNS server not reachable

### ISSUE THREAD

**Issue by MedicDok** [isontheline/pro.webssh.net#1039] opened 2024-01-22 11:41 UTC
# Bug description
iOS: 17.2

When I try to connect to a server, I get an error message: IP address could not be retrieved from DNS server.

I have blocked all DNS queries on port 53 for all computers, except for my gateway.

It seems that webssh wants to make dns queries to servers that are not running through my gateway. Could it be that in the iOS version of webssh the dns servers are hard coded?
On MacOS everything works as it should and there are no problems.

# Steps to reproduce
1.  Open WebSSH
2. Click on a server
3. Error is thrown

**Comment by isontheline** [comment] 2024-01-22 13:06
Hey @MedicDok 👋 

Could you tell me the exact WebSSH version you are running?

**Comment by MedicDok** [comment] 2024-01-22 13:14
iOS version 24.09. (the "about" information shows: 24.8.1244 @ Jan 14 2024 13:02:52)
I have no idea why different information is displayed.
Settings -> About WebSSH (24.8.1244 @ Jan 14 2024 13:02:52)
and 
Settings -> About WebSSH -> click on the field (24.09. - Dragon)

**Comment by MedicDok** [comment] 2024-01-22 13:36
I rarely use test flight apps. But I can test a WebSSH beta version if required.

**Comment by MedicDok** [comment] 2024-01-22 18:08
Screenshot:
![IMG_DA13D6026FCD-1](https://github.com/isontheline/pro.webssh.net/assets/155551402/a7aa53df-6953-4ce4-bd67-47801e9a9cd9)

**Comment by isontheline** [comment] 2024-01-22 18:48
@MedicDok Are you using IP or domain name for the hostname?

If you are using IP you shouldn't receive a such error and I need to Check what's wrong within WebSSH

**Comment by MedicDok** [comment] 2024-01-22 18:54
That is a good point. I have added all servers with an IP address but it still makes DNS queries

**Comment by isontheline** [comment] 2024-01-22 19:14
Definitely a bug on my side 😓

I'm making a fix and will push it tonight for beta release

Sorry for the trouble 

I'll come back to you shortly

**Comment by isontheline** [comment] 2024-01-22 22:15
A possible fix has been pushed to TestFlight. Waiting for approval.

I'll come back to you when available in a few hours

**Comment by isontheline** [comment] 2024-01-23 06:24
Hello @MedicDok 👋

Could you try this release please ?
https://testflight.apple.com/join/QSrBK59z

It contains fix about IP addresses

**Comment by MedicDok** [comment] 2024-01-23 06:28
Still the same error message.

**Comment by isontheline** [comment] 2024-01-23 06:30
@MedicDok Please post your verbose logs : 
https://webssh.net/documentation/help/howtos/enabling-verbose-logging/

They will contain some data to find the root cause

**Comment by MedicDok** [comment] 2024-01-23 08:41
I have looked at the log file. The correct DNS server is being used. The IP address from where WebSSH wants to connect is also correct. But it is still unclear why it wants to make a DNS query for an IP address.
[log-20240123.txt](https://github.com/isontheline/pro.webssh.net/files/14020976/log-20240123.txt)

**Comment by isontheline** [comment] 2024-01-23 10:09
@MedicDok Perfect!

Please confirm me that you have a trailing space on IP : 

Resolving '45.xxx.xxx.xxx '...

If it's the case then I will be able to fix this issue on my side.

Sorry again

**Comment by MedicDok** [comment] 2024-01-23 10:20
Original file: 9 '...

I can confirm, that there is a space after the IP.

**Comment by isontheline** [comment] 2024-01-23 10:27
🙏

A fix is on its way

**Comment by isontheline** [comment] 2024-01-23 11:28
Fix now available on WebSSH 24.9.1250 : https://testflight.apple.com/join/QSrBK59z

**Comment by MedicDok** [comment] 2024-01-23 11:30
Bug is fixed!

**Comment by isontheline** [comment] 2024-01-23 12:23
@MedicDok Many thanks for your feedback 🙏

24.9 release will be pushed soon to the App Store

I wish you a nice day ☀️

**Closed by isontheline** 2024-01-23 12:23 UTC
Labels: 🐛 bug
