### ISSUE TITLE
Map touch to mouse events in ssh

### ISSUE THREAD

**Issue by sgberman** [isontheline/pro.webssh.net#64] opened 2020-09-16 19:46 UTC
**Describe the feature**
Can you make the touch screen emulate a mouse?  This feature would be useful when editing a file in VIM to allow you to move the cursor to the location you point at with your finger thereby allowing for faster text editing.

**Comment by isontheline** [comment] 2020-09-16 19:50
Yes it should be possible to map touch to mouse events and it will be great I agree 👍

**Comment by isontheline** [comment] 2020-09-17 19:14
Finally it's a duplicate of #59

I'm closing this issue and will do the work on #59

**Comment by isontheline** [comment] 2021-08-29 20:34
Closing this in favor of https://github.com/isontheline/pro.webssh.net/issues/59

**Closed by isontheline** 2021-08-29 20:34 UTC
Labels: enhancement
