### ISSUE TITLE
Update of the Meslo Nerd Font

### ISSUE THREAD

**Issue by MilesTEG1** [isontheline/pro.webssh.net#1224] opened 2024-10-30 14:09 UTC
Hello,

I'm enjoyo,g the WebSSH client on my iPhone, and on my mac.
But, my customisation of prompt on my servers doesn't be well treated with the Nerd-Fonts you put in the app:
![CleanShot 2024-10-30 at 14 57 52@2x](https://github.com/user-attachments/assets/2ca9d151-5224-466a-99cb-8f949b9379d5)
Some icons are missing, and some are superposed.

On my iTerm2 console, I've got this:
![CleanShot 2024-10-30 at 14 58 47@2x](https://github.com/user-attachments/assets/ff8d2169-5ae6-456e-bdab-6c585dcafe44)

# Feature description
You should update the NerdFont to get the new icons because some are obsolete now.
And, can you please add `FiraCode Nerd Font` (not the mono version).

Look:
- the old icon of network: 
  `echo "\ufbf1"`
- the new icon of network:
  `echo "\uf06f3"`

In WebSSH:
![CleanShot 2024-10-30 at 15 02 24@2x](https://github.com/user-attachments/assets/cf2cae39-b575-4e7d-9c1e-2982f69763ec)

https://www.nerdfonts.com/cheat-sheet

# Screenshots / Draws
See previous screenshots

**Comment by isontheline** [comment] 2024-10-30 14:29
Hello @MilesTEG1 👋

I will take a look at it.

In the meantime, could you share some customization you have done on your ZSH in order to le me to reproduce?

**Comment by MilesTEG1** [comment] 2024-10-30 20:39
Hello @isontheline 
No problem, here my repo where I share some of my .zshrc customization :)
https://github.com/MilesTEG1/zsh_my_prompt_customization/blob/main/Linux-Proxmox/zshrc

And thanks for looking into it :)

**Comment by isontheline** [comment] 2024-10-30 20:52
Merci @MilesTEG1 🙏

I'm now working on it

**Comment by isontheline** [comment] 2024-10-30 21:13
When using FiraCode font I'm encountering this glitch :
<img width="631" alt="image" src="https://github.com/user-attachments/assets/889674e7-60d7-4030-98e5-fbc25dd9638c">

I don't see the new network icon

**Comment by MilesTEG1** [comment] 2024-10-30 22:39
> When using FiraCode font I'm encountering this glitch :
> 
> <img width="631" alt="image" src="https://github.com/user-attachments/assets/889674e7-60d7-4030-98e5-fbc25dd9638c">
> 
> 
> 
> I don't see the new network icon

Yeah... me too...
I use the icon directly, not the code \u....
I don't know why...

I think it's the same for other Nerd Font.

**Comment by isontheline** [comment] 2024-10-31 06:08
OK perfect so I continue my update about default nerd font

About FiraCode and others : did you know that you can install any MONO fonts by using the "ifont" app on the App Store? Then inside WebSSH edit your theme to use any mono fonts by using.

I think I can't add all fonts because of : 
* licensing
* binary weight

**Comment by MilesTEG1** [comment] 2024-10-31 08:00
> OK perfect so I continue my update about default nerd font
> 
> About FiraCode and others : did you know that you can install any MONO fonts by using the "ifont" app on the App Store? Then inside WebSSH edit your theme to use any mono fonts by using.

Ho! I didn't know this can be possible.
I just try iFont, but the FiraCode Nerd Font (custom .ttf) I installed with a profile on iOS doesn't appear in custom fonts, nor in app settings nor in WebSSH.
So it's not useful for me right now.

> I think I can't add all fonts because of : 
> * licensing
> * binary weight
Ho, damn...
Too bad then, I stick with the one you put 😊

**Comment by isontheline** [comment] 2024-10-31 12:35
> I just try iFont, but the FiraCode Nerd Font (custom .ttf) I installed with a profile on iOS doesn't appear in custom fonts, nor in app settings nor in WebSSH.

Have you tried the "mono" one?

**Comment by MilesTEG1** [comment] 2024-10-31 12:55
> > I just try iFont, but the FiraCode Nerd Font (custom .ttf) I installed with a profile on iOS doesn't appear in custom fonts, nor in app settings nor in WebSSH.
> 
> Have you tried the "mono" one?

What do you mean by the mono one?
FiraCode?
In which mode? Imported or featured?

**Comment by isontheline** [comment] 2024-11-01 08:54
By "mono" I mean this one :
<img width="516" alt="image" src="https://github.com/user-attachments/assets/8cdbe7df-09e6-4206-af90-55d494149857">

> In which mode? Imported or featured?

Imported. Featured doesn't contain FiraCode it seems.

**Comment by MilesTEG1** [comment] 2024-11-01 08:56
> By "mono" I mean this one : <img alt="image" width="516" src="https://private-user-images.githubusercontent.com/44212923/382234297-8cdbe7df-09e6-4206-af90-55d494149857.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTE2MTcsIm5iZiI6MTczMDQ1MTMxNywicGF0aCI6Ii80NDIxMjkyMy8zODIyMzQyOTctOGNkYmU3ZGYtMDllNi00MjA2LWFmOTAtNTVkNDk0MTQ5ODU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA4NTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYmRjNmIyOTlmNDUyOThhYmQ0MDFkMmI4ZTFlZTUzNzcyYzZmNDQ1NDZhZDg0NTQzNTdkNjM1ZmFkNjJlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wif-0vlQYuJ1-2z4JiaaREeLnAOsBO9UzY5rw-x5Q14">
> 
> > In which mode? Imported or featured?
> 
> Imported. Featured doesn't contain FiraCode it seems.

Ok, but the thing is the one I imported doesn't appears in the custom font in iOS settings, nor in the WebSSH font selection 😢

**Comment by isontheline** [comment] 2024-11-01 09:05
> FiraCode
> The OFL allows the licensed fonts to be used, studied, modified and
redistributed freely as long as they are not sold by themselves

I will try to include it, just an exception as I wouldn't like to increase WebSSH binary (already 200MB+)

**Comment by MilesTEG1** [comment] 2024-11-01 09:18
> > FiraCode
> 
> > The OFL allows the licensed fonts to be used, studied, modified and
> 
> redistributed freely as long as they are not sold by themselves
> 
> 
> 
> I will try to include it, just an exception as I wouldn't like to increase WebSSH binary (already 200MB+)

Maybe you can set an option to download the custom font for those who want's it?

**Comment by isontheline** [comment] 2024-11-01 09:19
Apple doesn't "like" to have apps to download external parts, I want to avoid review rejections as much as possible

**Comment by isontheline** [comment] 2024-11-01 10:45
You can try WebSSH 27.10.1428 : https://testflight.apple.com/join/QSrBK59z

**Comment by MilesTEG1** [comment] 2024-11-01 13:10
> You can try WebSSH 27.10.1428 : https://testflight.apple.com/join/QSrBK59z

Great 👍🏻 
![CleanShot 2024-11-01 at 13 50 41@2x](https://github.com/user-attachments/assets/d06f4361-41f8-4d7e-a6af-ef78cbd4b964)
![CleanShot 2024-11-01 at 13 59 11@2x](https://github.com/user-attachments/assets/7e0b9a4c-80ef-4a94-b9cf-3b5c3edc3808)

I don't understand why I have overlaping icon in segments...
If you knwo, I would be glad if you'll tell me how to fix it, otherwise, nevermind 😄

**Comment by isontheline** [comment] 2024-11-01 16:25
Aucune idée 🤷‍♂️

**Comment by isontheline** [comment] 2024-11-01 19:57
Will be released on the App Store on next week

**Closed by isontheline** 2024-11-01 19:57 UTC
Labels: ✨ enhancement
